# REPRESENTACION GRAMATICA 1
S ::= ControlesBlock

ControlesBlock ::= SIGNO_MENOR_QUE SIGNO_ADMIRACION_C SIGNO_GUION SIGNO_GUION RESERVADA_CONTROLES ControlList RESERVADA_CONTROLES SIGNO_GUION SIGNO_GUION SIGNO_MAYOR_QUE

ControlList ::= Control ControlList | $ 

Control ::= ControlType IDENTIFICADOR SIGNO_PUNTO_Y_COMA | COMENTARIO_LINEA

ControlType ::= RESERVADA_ETIQUETA
    | RESERVADA_BOTON
    | RESERVADA_CHECK
    | RESERVADA_RADIOBOTON
    | RESERVADA_TEXTO
    | RESERVADA_AREATEXTO
    | RESERVADA_CLAVE
    | RESERVADA_CONTENEDOR





# REPRESENTACION GRAMATICA 2
S ::= ControlesBlock

ControlesBlock ::= '<' '!' '-' '-' RESERVADA_CONTROLES ControlList RESERVADA_CONTROLES '-' '-' '>'

ControlList ::= Control ControlList
    |
Control ::= ControlType IDENTIFICADOR ';'
    | COMENTARIO_LINEA

ControlType ::= RESERVADA_ETIQUETA
    | RESERVADA_BOTON
    | RESERVADA_CHECK
    | RESERVADA_RADIOBOTON
    | RESERVADA_TEXTO
    | RESERVADA_AREATEXTO
    | RESERVADA_CLAVE
    | RESERVADA_CONTENEDOR